In [1]:
eye(3, 3)

3x3 Array{Float64,2}:
 1.0  0.0  0.0
 0.0  1.0  0.0
 0.0  0.0  1.0

In [2]:
diagm(collect(1:6))

6x6 Array{Int32,2}:
 1  0  0  0  0  0
 0  2  0  0  0  0
 0  0  3  0  0  0
 0  0  0  4  0  0
 0  0  0  0  5  0
 0  0  0  0  0  6

In [3]:
rand(3,3)

3x3 Array{Float64,2}:
 0.618052  0.261549  0.856381
 0.805495  0.611989  0.100097
 0.730698  0.541069  0.510894

In [4]:
rand(2,3)

2x3 Array{Float64,2}:
 0.295466  0.0303647  0.400187
 0.169877  0.763863   0.626885

In [5]:
rand(0:5,3,3)

3x3 Array{Int32,2}:
 4  2  3
 0  1  1
 0  5  1

In [6]:
trues(3, 4)

3x4 BitArray{2}:
 true  true  true  true
 true  true  true  true
 true  true  true  true

In [9]:
fill!(a, 0);

LoadError: LoadError: UndefVarError: a not defined
while loading In[9], in expression starting on line 1

In [13]:
fill!(a, 0)

LoadError: LoadError: UndefVarError: a not defined
while loading In[13], in expression starting on line 1

In [14]:
a = [2,3]

2-element Array{Int32,1}:
 2
 3

In [15]:
fill!(a, 0)

2-element Array{Int32,1}:
 0
 0

In [16]:
b = [range(1,10)]

10-element Array{Int32,1}:
  1
  2
  3
  4
  5
  6
  7
  8
  9
 10

 in depwarn at deprecated.jl:73
 in include_string at loading.jl:266
 in execute_request_0x535c5df2 at C:\Users\Vladimir Alencar\.julia\v0.4\IJulia\src\execute_request.jl:177
 in eventloop at C:\Users\Vladimir Alencar\.julia\v0.4\IJulia\src\IJulia.jl:141
 in anonymous at task.jl:447
while loading In[16], in expression starting on line 1


In [17]:
b

10-element Array{Int32,1}:
  1
  2
  3
  4
  5
  6
  7
  8
  9
 10

In [19]:
fill!(b, 0);

In [22]:
print(b);

[0,0,0,0,0,0,0,0,0,0]

In [24]:
print(b)

[0,0,0,0,0,0,0,0,0,0]

In [25]:
reshape(linspace(0, 100, 30), 10, 3)

10x3 Array{Float64,2}:
  0.0      34.4828   68.9655
  3.44828  37.931    72.4138
  6.89655  41.3793   75.8621
 10.3448   44.8276   79.3103
 13.7931   48.2759   82.7586
 17.2414   51.7241   86.2069
 20.6897   55.1724   89.6552
 24.1379   58.6207   93.1034
 27.5862   62.069    96.5517
 31.0345   65.5172  100.0   

In [28]:
reshape(rand(0:100,30), 10, 3)

10x3 Array{Int32,2}:
 55  84  36
  9  97  83
  6  83  99
 82  91  82
  4  48  95
 66  15  43
 22  31  20
 32  75  28
 15   0  42
 58  80  24

In [27]:
rand(0:100)

55

In [29]:
repmat([1, 2, 3], 2)

6-element Array{Int32,1}:
 1
 2
 3
 1
 2
 3

In [30]:
repeat([8, 10], inner = [2, 3])

4x3 Array{Int32,2}:
  8   8   8
  8   8   8
 10  10  10
 10  10  10

In [31]:
repeat([8, 10], outer = [2, 3])

4x3 Array{Int32,2}:
  8   8   8
 10  10  10
  8   8   8
 10  10  10

In [32]:
Array{Int64}(6)

6-element Array{Int64,1}:
 8183304270364940
 7866713641042212
 8938187722060900
 8938290801498548
 8824456988410916
          2180156

In [33]:
Array[1:3, 4:6]

2-element Array{Array{T,N},1}:
 [1,2,3]
 [4,5,6]

In [35]:
reshape([1,2,3,4,5,6,7,8], 4, 2)

4x2 Array{Int32,2}:
 1  5
 2  6
 3  7
 4  8

In [37]:
Array{AbstractString}(2, 3, 4)

2x3x4 Array{AbstractString,3}:
[:, :, 1] =
 #undef  #undef  #undef
 #undef  #undef  #undef

[:, :, 2] =
 #undef  #undef  #undef
 #undef  #undef  #undef

[:, :, 3] =
 #undef  #undef  #undef
 #undef  #undef  #undef

[:, :, 4] =
 #undef  #undef  #undef
 #undef  #undef  #undef

In [38]:
a = collect(1:10);
b = similar(a)

10-element Array{Int32,1}:
           4
 -2147483647
           0
           0
           0
    86188628
    86188628
    86188628
    86188628
    86188628

In [39]:
a

10-element Array{Int32,1}:
  1
  2
  3
  4
  5
  6
  7
  8
  9
 10

In [41]:
ab = a

10-element Array{Int32,1}:
  1
  2
  3
  4
  5
  6
  7
  8
  9
 10

In [42]:
ab

10-element Array{Int32,1}:
  1
  2
  3
  4
  5
  6
  7
  8
  9
 10

In [43]:
[1 0 ; 0 1]

2x2 Array{Int32,2}:
 1  0
 0  1

In [47]:
(1 0 
0 1)

LoadError: LoadError: syntax: missing separator in tuple
while loading In[47], in expression starting on line 1

In [48]:
 id  = reshape([1, 0, 0, 1], 2, 2)

2x2 Array{Int32,2}:
 1  0
 0  1

In [49]:
[12 23 344 45]

1x4 Array{Int32,2}:
 12  23  344  45

In [51]:
[[1,2,3]; [4,5,6]]

6-element Array{Int32,1}:
 1
 2
 3
 4
 5
 6

In [55]:
[1 2  3 ; 4 5 6]

2x3 Array{Int32,2}:
 1  2  3
 4  5  6

In [56]:
a = [10,20,30,40,50,60,70,80,90,100]

10-element Array{Int32,1}:
  10
  20
  30
  40
  50
  60
  70
  80
  90
 100

In [57]:
a[3]

30

In [58]:
a[end]

100

In [59]:
a2 = [1 2 3; 4 5 6; 7 8 9]

3x3 Array{Int32,2}:
 1  2  3
 4  5  6
 7  8  9

In [60]:
a2[2,3]

6

In [61]:
a2[:, 2]

3-element Array{Int32,1}:
 2
 5
 8

In [62]:
a2[2, :]

1x3 Array{Int32,2}:
 4  5  6

In [63]:
a = collect(1:10)

10-element Array{Int32,1}:
  1
  2
  3
  4
  5
  6
  7
  8
  9
 10

In [64]:
a * 2

10-element Array{Int32,1}:
  2
  4
  6
  8
 10
 12
 14
 16
 18
 20

In [67]:
 sin(collect(0:15:360))

25-element Array{Float64,1}:
  0.0      
  0.650288 
 -0.988032 
  0.850904 
 -0.304811 
 -0.387782 
  0.893997 
 -0.970535 
  0.580611 
  0.0883687
 -0.714876 
  0.997797 
 -0.801153 
  0.219455 
  0.467719 
 -0.930095 
  0.945445 
 -0.506392 
 -0.176046 
  0.773872 
 -0.999756 
  0.745133 
 -0.132382 
 -0.543996 
  0.958916 

In [65]:
collect(0:15:360)

25-element Array{Int32,1}:
   0
  15
  30
  45
  60
  75
  90
 105
 120
 135
 150
 165
 180
 195
 210
 225
 240
 255
 270
 285
 300
 315
 330
 345
 360

In [68]:
r = rand(0:10, 10)

10-element Array{Int32,1}:
  4
  3
  3
  0
  1
  9
  5
  5
  8
 10

In [73]:
minimum(r)

0

In [75]:
 a = rand(0:10,10, 10)

10x10 Array{Int32,2}:
 10   5   1   7   7   9   9   9  2  9
  4   8   3   9   8   6   0  10  0  8
  8  10   9   5   9   5   1   5  8  5
  9   6   3   3   9   3   8   0  4  8
 10   4  10   5   1   0   1   8  5  4
  1   3  10   1  10   1   2   3  9  6
  3   0   7   3   1   2   3   9  0  7
  8   1   7   8   2   7  10   1  2  1
 10   2   2  10   1   9   8   6  0  7
  7   3   0   8   2  10   0  10  7  4

In [77]:
maximum(a)

10

minimum(a)

In [78]:
minimum(a)


0

In [79]:
maximum(a)

10

In [ ]:
 a[a .== 0] = 11;

In [81]:
 a[a .== 0] = 77

77

In [82]:
a

10x10 Array{Int32,2}:
 10   5   1   7   7   9   9   9   2  9
  4   8   3   9   8   6  77  10  77  8
  8  10   9   5   9   5   1   5   8  5
  9   6   3   3   9   3   8  77   4  8
 10   4  10   5   1  77   1   8   5  4
  1   3  10   1  10   1   2   3   9  6
  3  77   7   3   1   2   3   9  77  7
  8   1   7   8   2   7  10   1   2  1
 10   2   2  10   1   9   8   6  77  7
  7   3  77   8   2  10  77  10   7  4

In [83]:
table = [r * c for r in 1:5, c in 1:5]

5x5 Array{Int32,2}:
 1   2   3   4   5
 2   4   6   8  10
 3   6   9  12  15
 4   8  12  16  20
 5  10  15  20  25

In [1]:
a=1

1

In [2]:
table = [r * c for r in 1:5, c in 1:5]

5x5 Array{Int32,2}:
 1   2   3   4   5
 2   4   6   8  10
 3   6   9  12  15
 4   8  12  16  20
 5  10  15  20  25

In [3]:
a=1

1

In [4]:
table[1,:]

1x5 Array{Int32,2}:
 1  2  3  4  5

In [5]:
table[:,2]

5-element Array{Int32,1}:
  2
  4
  6
  8
 10

In [6]:
 table[:]

25-element Array{Int32,1}:
  1
  2
  3
  4
  5
  2
  4
  6
  8
 10
  3
  6
  9
 12
 15
  4
  8
 12
 16
 20
  5
 10
 15
 20
 25

In [7]:
table[:,2:3]

5x2 Array{Int32,2}:
  2   3
  4   6
  6   9
  8  12
 10  15

In [8]:
table = [r * c for r in 1:5, c in 1:5]

5x5 Array{Int32,2}:
 1   2   3   4   5
 2   4   6   8  10
 3   6   9  12  15
 4   8  12  16  20
 5  10  15  20  25

In [9]:
 a = collect(1:10);

In [11]:
3 in a

true

In [74]:
maximum(r)

10

In [12]:
in(3, a)

true

In [4]:
primes = collect([1,2,3,5,7,11,13,17,19,23]);

In [5]:
print (primes)

[1,2,3,5,7,11,13,17,19,23]

In [16]:
primes = collect(1,2,3,5,7,11,13,17,19,23);

LoadError: LoadError: MethodError: `collect` has no method matching collect(::Int32, ::Int32, ::Int32, ::Int32, ::Int32, ::Int32, ::Int32, ::Int32, ::Int32, ::Int32)
Closest candidates are:
  collect{T}(!Matched::Type{T}, ::Any)
  collect(::Any)
while loading In[16], in expression starting on line 1

In [20]:
 primes = collect([1,2,3,5,7,11,13,17,19,23]);

In [23]:
print (primes)

[1,2,3,5,7,11,13,17,19,23]

In [24]:
findfirst(primes,13)

7

In [25]:
primes[7]

13

In [26]:
findfirst(x -> x == 13, primes)

7

In [27]:
print (primes)

[1,2,3,5,7,11,13,17,19,23]

In [7]:
fill(84, 42),

([84,84,84,84,84,84,84,84,84,84  …  84,84,84,84,84,84,84,84,84,84],)

In [28]:
print (primes)

[1,2,3,5,7,11,13,17,19,23]

In [29]:
findfirst(x -> x == 13, primes)

7

In [30]:
find(isinteger, primes)

10-element Array{Int32,1}:
  1
  2
  3
  4
  5
  6
  7
  8
  9
 10

In [31]:
print (primes)

[1,2,3,5,7,11,13,17,19,23]

In [35]:
primes[find(iseven, primes)]

1-element Array{Int32,1}:
 2

In [36]:
primes[find(isodd, primes)]

9-element Array{Int32,1}:
  1
  3
  5
  7
 11
 13
 17
 19
 23

In [6]:
primes[findfirst(iseven, primes)]

2

In [7]:
print(primes)

[1,2,3,5,7,11,13,17,19,23]

In [11]:
findnext(isodd, primes, 1 + findfirst(primes,13))

8

In [9]:
primes[findnext(isodd, primes, 1 + findfirst(primes,13))]

17

In [12]:
primes[ans]

17

In [13]:
findin(primes, [11,5])

2-element Array{Int32,1}:
 4
 6

In [14]:
print(primes)

[1,2,3,5,7,11,13,17,19,23]

In [15]:
a2 = [1 2 3; 4 5 6; 7 8 9]

3x3 Array{Int32,2}:
 1  2  3
 4  5  6
 7  8  9

In [16]:
ndims(a2)

2

In [17]:
size(a2)

(3,3)

In [18]:
length(a2)

9

In [19]:
countnz(a2)

9

In [20]:
 a2

3x3 Array{Int32,2}:
 1  2  3
 4  5  6
 7  8  9

In [21]:
 ind2sub(a2, 5)

(2,2)

In [24]:
for i in 1:length(a2)
    println(ind2sub(a2, i), " ", a2[i], " ",i)
    end

(1,1) 1 1
(2,1) 4 2
(3,1) 7 3
(1,2) 2 4
(2,2) 5 5
(3,2) 8 6
(1,3) 3 7
(2,3) 6 8
(3,3) 9 9


In [39]:
a2[sub2ind((3,3), 3,3)]

9

In [40]:
a2[sub2ind(size(a2),1,2)]

2

In [41]:
odds = collect(1:2:10)

5-element Array{Int32,1}:
 1
 3
 5
 7
 9

In [42]:
evens = collect(2:2:10)

5-element Array{Int32,1}:
  2
  4
  6
  8
 10

In [43]:
union(odds, evens)

10-element Array{Int32,1}:
  1
  3
  5
  7
  9
  2
  4
  6
  8
 10

In [44]:
intersect([1:10], [5:15])

6-element Array{Int32,1}:
  5
  6
  7
  8
  9
 10

 in depwarn at deprecated.jl:73
 in include_string at loading.jl:266
 in execute_request_0x535c5df2 at C:\Users\Vladimir Alencar\.julia\v0.4\IJulia\src\execute_request.jl:177
 in eventloop at C:\Users\Vladimir Alencar\.julia\v0.4\IJulia\src\IJulia.jl:141
 in anonymous at task.jl:447
while loading In[44], in expression starting on line 1
 in depwarn at deprecated.jl:73
 in include_string at loading.jl:266
 in execute_request_0x535c5df2 at C:\Users\Vladimir Alencar\.julia\v0.4\IJulia\src\execute_request.jl:177
 in eventloop at C:\Users\Vladimir Alencar\.julia\v0.4\IJulia\src\IJulia.jl:141
 in anonymous at task.jl:447
while loading In[44], in expression starting on line 1


In [51]:
intersect(collect(1:10), collect(5:15))

6-element Array{Int32,1}:
  5
  6
  7
  8
  9
 10

In [52]:
setdiff([1:15], [5:20])

4-element Array{Int32,1}:
 1
 2
 3
 4


 in depwarn at deprecated.jl:73
 in include_string at loading.jl:266
 in execute_request_0x535c5df2 at C:\Users\Vladimir Alencar\.julia\v0.4\IJulia\src\execute_request.jl:177
 in eventloop at C:\Users\Vladimir Alencar\.julia\v0.4\IJulia\src\IJulia.jl:141
 in anonymous at task.jl:447
while loading In[52], in expression starting on line 1
 in depwarn at deprecated.jl:73
 in include_string at loading.jl:266
 in execute_request_0x535c5df2 at C:\Users\Vladimir Alencar\.julia\v0.4\IJulia\src\execute_request.jl:177
 in eventloop at C:\Users\Vladimir Alencar\.julia\v0.4\IJulia\src\IJulia.jl:141
 in anonymous at task.jl:447
while loading In[52], in expression starting on line 1


In [53]:
filter(isprime, 1:100)

25-element Array{Int32,1}:
  2
  3
  5
  7
 11
 13
 17
 19
 23
 29
 31
 37
 41
 43
 47
 53
 59
 61
 67
 71
 73
 79
 83
 89
 97

In [56]:
filter(isodd, collect(1:20))

10-element Array{Int32,1}:
  1
  3
  5
  7
  9
 11
 13
 15
 17
 19

In [62]:
a = (filter(isodd, collect(1:20)))

10-element Array{Int32,1}:
  1
  3
  5
  7
  9
 11
 13
 15
 17
 19

In [65]:
length(a)

10

In [78]:
a = collect(10:100); 
i = rand(10:100)
print (i)
a[i]

71

80

In [76]:
a[53]

53

In [79]:
a = rand(100:110, 10)

10-element Array{Int32,1}:
 102
 101
 110
 100
 104
 102
 108
 102
 100
 110

In [80]:
extrema(a)

(100,110)

In [81]:
findmax(a)

(110,3)

In [82]:
 sum(a)

1039

In [83]:
mean(a)

103.9

In [84]:
middle(a)

105.0

In [85]:
collect(combinations(a, 3))

120-element Array{Array{Int32,1},1}:
 [102,101,110]
 [102,101,100]
 [102,101,104]
 [102,101,102]
 [102,101,108]
 [102,101,102]
 [102,101,100]
 [102,101,110]
 [102,110,100]
 [102,110,104]
 [102,110,102]
 [102,110,108]
 [102,110,102]
 ⋮            
 [104,102,110]
 [104,100,110]
 [102,108,102]
 [102,108,100]
 [102,108,110]
 [102,102,100]
 [102,102,110]
 [102,100,110]
 [108,102,100]
 [108,102,110]
 [108,100,110]
 [102,100,110]

In [86]:
a

10-element Array{Int32,1}:
 102
 101
 110
 100
 104
 102
 108
 102
 100
 110

In [87]:
a = collect(1:10)

10-element Array{Int32,1}:
  1
  2
  3
  4
  5
  6
  7
  8
  9
 10

In [89]:
permutations(a)

Base.Permutations{Array{Int32,1}}([1,2,3,4,5,6,7,8,9,10])

In [90]:
a = collect(1:10); push!(a, 20)

11-element Array{Int32,1}:
  1
  2
  3
  4
  5
  6
  7
  8
  9
 10
 20

In [91]:
unshift!(a, 0)

12-element Array{Int32,1}:
  0
  1
  2
  3
  4
  5
  6
  7
  8
  9
 10
 20

In [96]:
a

10-element Array{Int32,1}:
  1
  2
  3
  4
  5
  6
  7
  8
  9
 10

In [93]:
 pop!(a)

20

In [95]:
shift!(a)

0

In [1]:
deleteat!([1:10],3)

9-element Array{Int32,1}:
  1
  2
  4
  5
  6
  7
  8
  9
 10

 in depwarn at deprecated.jl:73
 in include_string at loading.jl:266
 in execute_request_0x535c5df2 at C:\Users\Vladimir Alencar\.julia\v0.4\IJulia\src\execute_request.jl:177
 in eventloop at C:\Users\Vladimir Alencar\.julia\v0.4\IJulia\src\IJulia.jl:141
 in anonymous at task.jl:447
while loading In[1], in expression starting on line 1


In [2]:
a = [1, 2, 3, 6, 7, 8, 9]

7-element Array{Int32,1}:
 1
 2
 3
 6
 7
 8
 9

In [3]:
splice!(a, 4:5, 4:6)

2-element Array{Int32,1}:
 6
 7

In [4]:
a

8-element Array{Int32,1}:
 1
 2
 3
 4
 5
 6
 8
 9

In [5]:
a = collect(1:10); 
splice!(a,5);
a

9-element Array{Int32,1}:
  1
  2
  3
  4
  6
  7
  8
  9
 10

In [6]:
a[1:10] = -1

LoadError: LoadError: BoundsError: attempt to access 9-element Array{Int32,1}:
 -1
 -1
 -1
 -1
 -1
 -1
 -1
 -1
 -1
  at index [10]
while loading In[6], in expression starting on line 1

In [7]:
a

9-element Array{Int32,1}:
 -1
 -1
 -1
 -1
 -1
 -1
 -1
 -1
 -1

In [8]:
setindex!(a,1:10,10:-1:1)

LoadError: LoadError: BoundsError: attempt to access 9-element Array{Int32,1}:
 -1
 -1
 -1
 -1
 -1
 -1
 -1
 -1
 -1
  at index [10]
while loading In[8], in expression starting on line 1

In [9]:
a = collect(1:10);

In [10]:
print(a)

[1,2,3,4,5,6,7,8,9,10]

In [11]:
 b = a[:]

10-element Array{Int32,1}:
  1
  2
  3
  4
  5
  6
  7
  8
  9
 10

In [12]:
function set_to_5(x)
        x = 5
        end

set_to_5 (generic function with 1 method)

In [13]:
x = 3

3

In [14]:
set_to_5(x)

5

In [15]:
x

3

In [16]:
function fill_with_5(x)
         x[:] = 5
       end

fill_with_5 (generic function with 1 method)

In [18]:
x = collect(1:10)

10-element Array{Int32,1}:
  1
  2
  3
  4
  5
  6
  7
  8
  9
 10

In [19]:
fill_with_5(x)

5

In [20]:
x

10-element Array{Int32,1}:
 5
 5
 5
 5
 5
 5
 5
 5
 5
 5

In [1]:
 A = reshape(1:12, 3, 4)

3x4 Array{Int32,2}:
 1  4  7  10
 2  5  8  11
 3  6  9  12

In [6]:
z = [collect(1:12)]

12-element Array{Int32,1}:
  1
  2
  3
  4
  5
  6
  7
  8
  9
 10
 11
 12

 in depwarn at deprecated.jl:73
 in include_string at loading.jl:266
 in execute_request_0x535c5df2 at C:\Users\Vladimir Alencar\.julia\v0.4\IJulia\src\execute_request.jl:177
 in eventloop at C:\Users\Vladimir Alencar\.julia\v0.4\IJulia\src\IJulia.jl:141
 in anonymous at task.jl:447
while loading In[6], in expression starting on line 1


In [7]:
z = reshape(z, 3,4)

3x4 Array{Int32,2}:
 1  4  7  10
 2  5  8  11
 3  6  9  12

In [8]:
fill("hi", 2, 2)

2x2 Array{ASCIIString,2}:
 "hi"  "hi"
 "hi"  "hi"

In [10]:
A

3x4 Array{Int32,2}:
 1  4  7  10
 2  5  8  11
 3  6  9  12

In [11]:
B = ones(3,4)

3x4 Array{Float64,2}:
 1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0

In [12]:
A + B

3x4 Array{Float64,2}:
 2.0  5.0   8.0  11.0
 3.0  6.0   9.0  12.0
 4.0  7.0  10.0  13.0

In [13]:
A = [1 2 ; 3 4]

2x2 Array{Int32,2}:
 1  2
 3  4

In [15]:
B = [10 11 ; 12 13]

2x2 Array{Int32,2}:
 10  11
 12  13

In [16]:
A .* B

2x2 Array{Int32,2}:
 10  22
 36  52

In [17]:
A * B

2x2 Array{Int32,2}:
 34  37
 78  85

In [18]:
[1 2 3 4 5] * 2

1x5 Array{Int32,2}:
 2  4  6  8  10

In [19]:
A .< 6

2x2 BitArray{2}:
 true  true
 true  true

In [20]:
A = reshape(1:12, 3, 4)

3x4 Array{Int32,2}:
 1  4  7  10
 2  5  8  11
 3  6  9  12

In [21]:
V = collect(1:4)

4-element Array{Int32,1}:
 1
 2
 3
 4

In [22]:
 A * V

3-element Array{Int32,1}:
 70
 80
 90

In [23]:
dot([1:3...], [21:23...])

134

In [26]:
a = collect(1:100)

100-element Array{Int32,1}:
   1
   2
   3
   4
   5
   6
   7
   8
   9
  10
  11
  12
  13
   ⋮
  89
  90
  91
  92
  93
  94
  95
  96
  97
  98
  99
 100

In [27]:
for i = 1:100
    push!(a, i)
end
print(a)

[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100]

In [32]:
A = rand(2:10, 3, 3)

3x3 Array{Int32,2}:
  5  9  4
 10  7  9
 10  5  3

In [33]:
det(A)

340.0

In [34]:
inv(A)

3x3 Array{Float64,2}:
 -0.0705882  -0.0205882   0.155882 
  0.176471   -0.0735294  -0.0147059
 -0.0588235   0.191176   -0.161765 

In [35]:
trace(A)

15

In [36]:
A = reshape(1:9, 3, 3)

3x3 Array{Int32,2}:
 1  4  7
 2  5  8
 3  6  9

In [37]:
sum(A)

45

In [38]:
mean(A)

5.0

In [39]:
 norm(A)

16.848103352614206

In [40]:
norm(A,1)

24.0

In [42]:
norm(A, Inf)

18.0

In [46]:
K = sort(A,1)

3x3 Array{Int32,2}:
 1  4  7
 2  5  8
 3  6  9

In [47]:
rp = randperm(10)

10-element Array{Int32,1}:
  8
  5
  2
  3
  4
  1
  7
  6
 10
  9

In [48]:
sort(rp)

10-element Array{Int32,1}:
  1
  2
  3
  4
  5
  6
  7
  8
  9
 10

In [49]:
 r = ["1E10", "150", "25", "3", "1.5", "1E-10", "0.5", ".999"];

In [50]:
sort(r)

8-element Array{ASCIIString,1}:
 ".999" 
 "0.5"  
 "1.5"  
 "150"  
 "1E-10"
 "1E10" 
 "25"   
 "3"    

In [51]:
table = collect(enumerate(rand(1:100, 10)))

10-element Array{Tuple{Int32,Int32},1}:
 (1,73) 
 (2,81) 
 (3,43) 
 (4,77) 
 (5,26) 
 (6,13) 
 (7,63) 
 (8,77) 
 (9,52) 
 (10,36)

In [52]:
sort(table, by= x -> x[2])

10-element Array{Tuple{Int32,Int32},1}:
 (6,13) 
 (5,26) 
 (10,36)
 (3,43) 
 (9,52) 
 (7,63) 
 (1,73) 
 (4,77) 
 (8,77) 
 (2,81) 

In [59]:
vowelcount(string) = count(c -> (c in "aeiou"), lowercase(string))

vowelcount (generic function with 1 method)

In [60]:
print(vowelcount("testesa"))

3

In [61]:
sentence = split("Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.");

In [62]:
sentence

19-element Array{SubString{ASCIIString},1}:
 "Lorem"      
 "ipsum"      
 "dolor"      
 "sit"        
 "amet,"      
 "consectetur"
 "adipisicing"
 "elit,"      
 "sed"        
 "do"         
 "eiusmod"    
 "tempor"     
 "incididunt" 
 "ut"         
 "labore"     
 "et"         
 "dolore"     
 "magna"      
 "aliqua."    

In [63]:
sort(sentence, lt = (x,y) -> vowelcount(x) > vowelcount(y))

19-element Array{SubString{ASCIIString},1}:
 "adipisicing"
 "consectetur"
 "eiusmod"    
 "incididunt" 
 "aliqua."    
 "labore"     
 "dolore"     
 "Lorem"      
 "ipsum"      
 "dolor"      
 "amet,"      
 "elit,"      
 "tempor"     
 "magna"      
 "sit"        
 "sed"        
 "do"         
 "ut"         
 "et"         

In [2]:
table = rand(1:4, 10, 10)

10x10 Array{Int32,2}:
 1  1  3  3  4  2  4  3  1  3
 4  3  3  4  4  3  1  3  2  2
 2  2  3  4  2  4  4  2  2  3
 1  2  1  4  3  4  1  4  3  4
 1  2  4  2  3  1  2  2  3  1
 1  2  3  1  1  3  2  2  4  4
 1  4  3  2  4  1  4  3  1  2
 1  4  1  1  1  2  3  2  1  4
 3  2  1  2  4  2  3  1  3  4
 1  3  2  3  4  4  3  3  1  4

In [3]:
table

10x10 Array{Int32,2}:
 1  1  3  3  4  2  4  3  1  3
 4  3  3  4  4  3  1  3  2  2
 2  2  3  4  2  4  4  2  2  3
 1  2  1  4  3  4  1  4  3  4
 1  2  4  2  3  1  2  2  3  1
 1  2  3  1  1  3  2  2  4  4
 1  4  3  2  4  1  4  3  1  2
 1  4  1  1  1  2  3  2  1  4
 3  2  1  2  4  2  3  1  3  4
 1  3  2  3  4  4  3  3  1  4

In [12]:
sortrows(table)

10x10 Array{Int32,2}:
 1  1  3  3  4  2  4  3  1  3
 1  2  1  4  3  4  1  4  3  4
 1  2  3  1  1  3  2  2  4  4
 1  2  4  2  3  1  2  2  3  1
 1  3  2  3  4  4  3  3  1  4
 1  4  1  1  1  2  3  2  1  4
 1  4  3  2  4  1  4  3  1  2
 2  2  3  4  2  4  4  2  2  3
 3  2  1  2  4  2  3  1  3  4
 4  3  3  4  4  3  1  3  2  2

In [5]:
print (t)

(10,10)

In [13]:
sortrows(table, by = x -> (x[1], x[2], x[3]))

10x10 Array{Int32,2}:
 1  1  3  3  4  2  4  3  1  3
 1  2  1  4  3  4  1  4  3  4
 1  2  3  1  1  3  2  2  4  4
 1  2  4  2  3  1  2  2  3  1
 1  3  2  3  4  4  3  3  1  4
 1  4  1  1  1  2  3  2  1  4
 1  4  3  2  4  1  4  3  1  2
 2  2  3  4  2  4  4  2  2  3
 3  2  1  2  4  2  3  1  3  4
 4  3  3  4  4  3  1  3  2  2

In [14]:
t = (1, 2, 3, 4, 5, 6, 7, 8, 9, 10)

(1,2,3,4,5,6,7,8,9,10)