In [5]:
x=4


4

In [6]:
x > 3 ? "yes" : "no"

"yes"

In [7]:
n = 1000003

 isprime(n) && "It's a prime!"

"It's a prime!"

In [8]:
name = "Brinkley"

     if name == "Jeeves"
           println("Very Good Jeeves")
       elseif name == "Brinkley"
           println("Thank you, Brinkley")
           println("and shut the door behind you")
       else
           println("Fine, just ignore me")
       end

Thank you, Brinkley
and shut the door behind you


In [9]:
for i in 0:10:100
            println(i)
       end

0
10
20
30
40
50
60
70
80
90
100


In [10]:
for color in ["red", "green", "blue"] # an array
           print(color, " ")
       end

red green blue 

In [11]:
for letter in "julia" # a string
           print(letter, " ")
       end

j u l i a 

In [12]:
for i in Dict("A"=>1, "B"=>2) # a dictionary
       println(i)
       end

"A"=>1
"B"=>2


In [14]:
d = Dict("b",8)

Dict{Any,Any} with 1 entry:
  'b' => 8


 in depwarn at deprecated.jl:73
 in include_string at loading.jl:266
 in execute_request_0x535c5df2 at C:\Users\Vladimir Alencar\.julia\v0.4\IJulia\src\execute_request.jl:177
 in eventloop at C:\Users\Vladimir Alencar\.julia\v0.4\IJulia\src\IJulia.jl:141
 in anonymous at task.jl:447
while loading In[14], in expression starting on line 1


In [15]:
d

Dict{Any,Any} with 1 entry:
  'b' => 8

In [16]:
d += Dict("A",1)

LoadError: LoadError: MethodError: `+` has no method matching +(::Dict{Any,Any}, ::Dict{Any,Any})
Closest candidates are:
  +(::Any, ::Any, !Matched::Any, !Matched::Any...)
while loading In[16], in expression starting on line 1


 in depwarn at deprecated.jl:73
 in include_string at loading.jl:266
 in execute_request_0x535c5df2 at C:\Users\Vladimir Alencar\.julia\v0.4\IJulia\src\execute_request.jl:177
 in eventloop at C:\Users\Vladimir Alencar\.julia\v0.4\IJulia\src\IJulia.jl:141
 in anonymous at task.jl:447
while loading In[16], in expression starting on line 1


In [18]:
d!("A",1)

LoadError: LoadError: UndefVarError: d! not defined
while loading In[18], in expression starting on line 1

In [19]:
d["h"] = 4

4

In [20]:
d

Dict{Any,Any} with 2 entries:
  'b' => 8
  "h" => 4

In [21]:
for i in Dict("A"=>1, "B"=>2) # a dictionary
       println(i)
       end

"A"=>1
"B"=>2


In [22]:
for i in Set(["a", "e", "a", "e", "i", "o", "i", "o", "u"])
       println(i)
       end

i
u
a
e
o


In [23]:
a = reshape(1:100, (10, 10))

10x10 Array{Int32,2}:
  1  11  21  31  41  51  61  71  81   91
  2  12  22  32  42  52  62  72  82   92
  3  13  23  33  43  53  63  73  83   93
  4  14  24  34  44  54  64  74  84   94
  5  15  25  35  45  55  65  75  85   95
  6  16  26  36  46  56  66  76  86   96
  7  17  27  37  47  57  67  77  87   97
  8  18  28  38  48  58  68  78  88   98
  9  19  29  39  49  59  69  79  89   99
 10  20  30  40  50  60  70  80  90  100

In [28]:
b = reshape(0:5,(3,2))

3x2 Array{Int32,2}:
 0  3
 1  4
 2  5

In [29]:
for n in a
       print(n, " ")
       end

1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99 100 

In [30]:
S = [n for n in 1:10]

10-element Array{Int32,1}:
  1
  2
  3
  4
  5
  6
  7
  8
  9
 10

In [31]:
print (S)

[1,2,3,4,5,6,7,8,9,10]

In [32]:
[i^2 for i in 1:10]

10-element Array{Int32,1}:
   1
   4
   9
  16
  25
  36
  49
  64
  81
 100

In [33]:
[i => i^2 for i in 1:10]

Dict{Int32,Int32} with 10 entries:
  4  => 16
  6  => 36
  10 => 100
  7  => 49
  5  => 25
  3  => 9
  8  => 64
  2  => 4
  1  => 1
  9  => 81

In [34]:
[(r,c) for r in 1:5, c in 1:5]

5x5 Array{Tuple{Int32,Int32},2}:
 (1,1)  (1,2)  (1,3)  (1,4)  (1,5)
 (2,1)  (2,2)  (2,3)  (2,4)  (2,5)
 (3,1)  (3,2)  (3,3)  (3,4)  (3,5)
 (4,1)  (4,2)  (4,3)  (4,4)  (4,5)
 (5,1)  (5,2)  (5,3)  (5,4)  (5,5)

In [35]:
m = rand(0:9, 3, 3)

3x3 Array{Int32,2}:
 5  5  7
 0  6  9
 3  7  3

In [36]:
[i for i in enumerate(m)]

9-element Array{Tuple{Int32,Any},1}:
 (1,5)
 (2,0)
 (3,3)
 (4,5)
 (5,6)
 (6,7)
 (7,7)
 (8,9)
 (9,3)

In [38]:
for i in zip(0:10, 100:110, 200:210)
    println(i) end

(0,100,200)
(1,101,201)
(2,102,202)
(3,103,203)
(4,104,204)
(5,105,205)
(6,106,206)
(7,107,207)
(8,108,208)
(9,109,209)
(10,110,210)


In [39]:
[i for i in 0:2:100]

51-element Array{Int32,1}:
   0
   2
   4
   6
   8
  10
  12
  14
  16
  18
  20
  22
  24
   ⋮
  78
  80
  82
  84
  86
  88
  90
  92
  94
  96
  98
 100

In [40]:
collect(0:25:100)

5-element Array{Int32,1}:
   0
  25
  50
  75
 100

In [41]:
collect(permutations([1:4]))

24-element Array{Array{Int32,1},1}:
 [1,2,3,4]
 [1,2,4,3]
 [1,3,2,4]
 [1,3,4,2]
 [1,4,2,3]
 [1,4,3,2]
 [2,1,3,4]
 [2,1,4,3]
 [2,3,1,4]
 [2,3,4,1]
 [2,4,1,3]
 [2,4,3,1]
 [3,1,2,4]
 [3,1,4,2]
 [3,2,1,4]
 [3,2,4,1]
 [3,4,1,2]
 [3,4,2,1]
 [4,1,2,3]
 [4,1,3,2]
 [4,2,1,3]
 [4,2,3,1]
 [4,3,1,2]
 [4,3,2,1]


 in depwarn at deprecated.jl:73
 in include_string at loading.jl:266
 in execute_request_0x535c5df2 at C:\Users\Vladimir Alencar\.julia\v0.4\IJulia\src\execute_request.jl:177
 in eventloop at C:\Users\Vladimir Alencar\.julia\v0.4\IJulia\src\IJulia.jl:141
 in anonymous at task.jl:447
while loading In[41], in expression starting on line 1


In [42]:
for x in 1:10, y in 1:10
          @show (x, y)
       end

(x,y) = (1,1)
(x,y) = (1,2)
(x,y) = (1,3)
(x,y) = (1,4)
(x,y) = (1,5)
(x,y) = (1,6)
(x,y) = (1,7)
(x,y) = (1,8)
(x,y) = (1,9)
(x,y) = (1,10)
(x,y) = (2,1)
(x,y) = (2,2)
(x,y) = (2,3)
(x,y) = (2,4)
(x,y) = (2,5)
(x,y) = (2,6)
(x,y) = (2,7)
(x,y) = (2,8)
(x,y) = (2,9)
(x,y) = (2,10)
(x,y) = (3,1)
(x,y) = (3,2)
(x,y) = (3,3)
(x,y) = (3,4)
(x,y) = (3,5)
(x,y) = (3,6)
(x,y) = (3,7)
(x,y) = (3,8)
(x,y) = (3,9)
(x,y) = (3,10)
(x,y) = (4,1)
(x,y) = (4,2)
(x,y) = (4,3)
(x,y) = (4,4)
(x,y) = (4,5)
(x,y) = (4,6)
(x,y) = (4,7)
(x,y) = (4,8)
(x,y) = (4,9)
(x,y) = (4,10)
(x,y) = (5,1)
(x,y) = (5,2)
(x,y) = (5,3)
(x,y) = (5,4)
(x,y) = (5,5)
(x,y) = (5,6)
(x,y) = (5,7)
(x,y) = (5,8)
(x,y) = (5,9)
(x,y) = (5,10)
(x,y) = (6,1)
(x,y) = (6,2)
(x,y) = (6,3)
(x,y) = (6,4)
(x,y) = (6,5)
(x,y) = (6,6)
(x,y) = (6,7)
(x,y) = (6,8)
(x,y) = (6,9)
(x,y) = (6,10)
(x,y) = (7,1)
(x,y) = (7,2)
(x,y) = (7,3)
(x,y) = (7,4)
(x,y) = (7,5)
(x,y) = (7,6)
(x,y) = (7,7)
(x,y) = (7,8)
(x,y) = (7,9)
(x,y) = (7,10)
(x,y) = (8,1)

In [43]:
x=0

0

In [44]:
while x < 4
    println(x)
    x += 1
end

0
1
2
3


In [45]:
s = "string";
       try
          s[1] = "p"
       catch e
          println("caught an error $e")
          println("but we can continue with execution")
       end

caught an error MethodError(setindex!,("string","p",1))
but we can continue with execution


In [46]:
primes = {1
  2
  3
  5
  7
 11
 13
 17
 19
 23}

10-element Array{Any,1}:
  1
  2
  3
  5
  7
 11
 13
 17
 19
 23

In [47]:
find(x -> x == 13, primes)

1-element Array{Int32,1}:
 7